import Dashboardlayout from "@/components/layout/dashboard/dashboard";
import ProductForm from "@/components/pages/dashboard/products/ProductForm";
import { baseurl } from "@/config/setting";
import Head from "next/head";
import { useParams } from "next/navigation";
import React from "react";

export const metadata = {
  title: "Edit Product",
  description: "Generated by create next app",
  metadata: {},
};

async function getCategories() {
  const res = await fetch(baseurl+`/categories`)
  const data = await res.json();
  return data
}

async function getBrands() {
  const res = await fetch(baseurl+`/brands`)
  const data = await res.json();
  return data
}


const Page = async () => {
  const category = await getCategories()
  const brands = await getBrands()



  return (
    <>
      <Dashboardlayout>
      <ProductForm data={{category,brands}} />
      </Dashboardlayout>
    </>
  );
};

export default Page;
