import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Dashboardlayout from "@/components/layout/dashboard/dashboard";
import ProductForm from "@/components/pages/dashboard/products/ProductForm";
import ProductServices from "@/helper/services/ProductServices";
import { getServerSession } from "next-auth";
import React from "react";

export const metadata = {
  title: "Edit Product",
  description: "Generated by create next app",
  metadata: {},
};




const Page = async ({params}) => {
  // const category = await getCategories()
  // const brands = await getBrands()
  // console.log(params);
  
  const result = await getRecord(params)

  // console.log(result);
  

  return (
    <>
      <Dashboardlayout>
        <ProductForm data={product.results} />
      </Dashboardlayout>
    </>
  );
};

export default Page;


export const getRecord = async (params) => {
  console.log(params);
  
  const product = await ProductServices.getSingleProducts(params.productID, params.token)
  const brands = await masterServices.getAllBrands({},params.token)
  const category = await masterServices.getAllcategories({},params.token)
  
  return { product, brands, category }

}
