import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import Dashboardlayout from "@/components/layout/dashboard/dashboard";
import ProductForm from "@/components/pages/dashboard/products/ProductForm";
import ProductServices from "@/helper/services/ProductServices";
import { getServerSession } from "next-auth";
import React from "react";

export const metadata = {
  title: "Edit Product",
  description: "Generated by create next app",
  metadata: {},
};




const Page = async (props) => {

  const session = await getServerSession(authOptions);
  const product = await ProductServices.getSingleProducts(props.params.productID, session["accessToken"])

  return (
    <>
      <Dashboardlayout>
        <ProductForm data={product.results} />
      </Dashboardlayout>
    </>
  );
};

export default Page;


